#=========================================================================
# Custom Scripts -- Tile Array CTS sink_type overrides
#=========================================================================

name: custom-cts-overrides

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------
commands:
  - mkdir -p outputs
  - envsubst '${array_width}' < cts_overrides.tcl > outputs/cts_overrides.tcl

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  - array_width: undefined

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - cts-overrides.tcl
