steps:
- label: 'PowerFlow'
  commands:
  - source ./.buildkite/setup.sh
  - echo "--- INFO"
  - cd tapeout_16
  - pwd

  - set -x

  - echo "+++ RUNNING SYNTHESIS"
  - ./gen_rtl.sh
  - ./run_synthesis.csh Tile_MemCore 1
