steps:
- label: 'PowerFlow'
  commands:
  - ./.buildkite/gen.sh -v

  - mkdir tapeout_16/power_reports

    #- ./.buildkite/syn.sh -v Tile_MemCore conv_3_3
    #- ./.buildkite/report.sh Tile_MemCore
    #- ./.buildkite/syn.sh -q Tile_MemCore harris
    #- ./.buildkite/report.sh Tile_MemCore
    #- ./.buildkite/syn.sh -q Tile_MemCore avg_pool 
    #- ./.buildkite/report.sh Tile_MemCore
    #- ./.buildkite/syn.sh -q Tile_MemCore upsample 
    #- ./.buildkite/report.sh Tile_MemCore
    #- ./.buildkite/syn.sh -q Tile_MemCore unet_example
    #- ./.buildkite/report.sh Tile_MemCore
    #- ./.buildkite/syn.sh -q Tile_MemCore strided_conv
    #- ./.buildkite/report.sh Tile_MemCore
  - ./.buildkite/syn.sh -v Tile_PE conv_3_3_add
  - ./.buildkite/report.sh Tile_PE
    #- ./.buildkite/syn.sh -v Tile_PE conv_3_3_mul
    #- ./.buildkite/report.sh Tile_PE
    #- ./.buildkite/syn.sh -v Garnet TOP
    #- ./.buildkite/report.sh Garnet
    
  artifact_paths:
    - "tapeout_16/**/*.power"
